"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['watermark.py']
DATA_FILES = []
OPTIONS = {}

OPTIONS.update(
    iconfile="assets/Icon.icns",
    plist=dict(
        CFBundleIdentifier='de.contmp.watermark',
        CFBundleDocumentTypes=[
            dict(
                CFBundleTypeExtensions=["png", "jpg", "jpeg"],
                CFBundleTypeName="Image",
                CFBundleTypeRole="Viewer"
            ),
        ]
    ),
    argv_emulation=1,
)
setup(
    app=APP,
    name='Watermark',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
