"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['source/watermark.py']
DATA_FILES = [
    'source/watermarker',
]
OPTIONS = {}

OPTIONS.update(
    argv_emulation=True,
    iconfile="assets/Icon.icns",
    plist=dict(
        CFBundleIdentifier='de.contmp.watermark',
        NSHumanReadableCopyright='Copyright © 2020, Bastian Probian, All Rights Reserved',
        CFBundleDocumentTypes=[
            dict(
                CFBundleTypeExtensions=["png", "jpg", "jpeg"],
                CFBundleTypeName="Image",
                CFBundleTypeRole="Viewer"
            ),
        ]
    ),
    packages=['PIL', 'pync']
)
setup(
    app=APP,
    name='Watermark',
    data_files=DATA_FILES,
    options={
        'py2app': OPTIONS,
    },
    setup_requires=['py2app'],
)
